In [2]:
import pandas as pd
import numpy as np
import zipfile
import csv
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


teste_list = ['VS1', 'TS1', 'TS2', 'TS3', 'TS4','SE', 'PS1', 'PS2', 'PS3', 'PS4', 'PS5',
              'PS6', 'EPS1', 'CP']

teste_list = [s + '_normalized.csv' for s in teste_list]

new_df = {}
master_df = pd.DataFrame()

# This code is for the normalized data
for key in teste_list:
        df = pd.read_table(key, header=None)
        master_df = pd.concat([master_df, df], axis=1)

In [3]:
target_df = pd.read_table('profile.csv', header=None)
target_df = target_df.drop([1,2,3,4], axis=1)

x_train, x_test, y_train, y_test = train_test_split(master_df, target_df, test_size=0.3, random_state=42)
knn = KNeighborsClassifier(n_neighbors=4)

knn.fit(x_train, y_train.values.ravel())
print(knn.score(x_test, y_test))

0.8806646525679759


In [4]:
pred = knn.predict(x_test)
y_train_pred = knn.predict(x_train)
cm_train = confusion_matrix(y_train, y_train_pred)
cm_test = confusion_matrix(y_test, pred)
print('confusion matrix treino\n',cm_train,'\n')
print('confusion matrix teste\n', cm_test,'\n')

confusion matrix treino
 [[501   1   0]
 [ 87 435   0]
 [  0  34 485]] 

confusion matrix teste
 [[230   0   0]
 [ 50 160   0]
 [  0  29 193]] 



In [5]:
print('Classification report treino\n',classification_report(y_train, y_train_pred),'\n')
print('Classification report teste\n',classification_report(y_test, pred),'\n')

Classification report treino
              precision    recall  f1-score   support

          3       0.85      1.00      0.92       502
         20       0.93      0.83      0.88       522
        100       1.00      0.93      0.97       519

avg / total       0.93      0.92      0.92      1543
 

Classification report teste
              precision    recall  f1-score   support

          3       0.82      1.00      0.90       230
         20       0.85      0.76      0.80       210
        100       1.00      0.87      0.93       222

avg / total       0.89      0.88      0.88       662
 



In [1]:
import pandas as pd
import numpy as np
import zipfile
import csv
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import timeit

start = timeit.default_timer()


teste_list = ['VS1', 'TS1', 'TS2', 'TS3', 'TS4','SE', 'PS1', 'PS2', 'PS3', 'PS4', 'PS5',
              'PS6', 'EPS1', 'CP']

teste_list = [s + '_normalized.csv' for s in teste_list]

new_df = {}
master_df = pd.DataFrame()

# This code is for the normalized data
for key in teste_list:
        df = pd.read_table(key, header=None)
        master_df = pd.concat([master_df, df], axis=1)

target_df = pd.read_table('profile.csv', header=None)
target_df = target_df.drop([1,2,3,4], axis=1)

x_train, x_test, y_train, y_test = train_test_split(master_df, target_df, test_size=0.3, random_state=42)
knn = KNeighborsClassifier(n_neighbors=4)

knn.fit(x_train, y_train.values.ravel())
print(knn.score(x_test, y_test))
pred = knn.predict(x_test)
y_train_pred = knn.predict(x_train)
cm_train = confusion_matrix(y_train, y_train_pred)
cm_test = confusion_matrix(y_test, pred)
print('confusion matrix teste\n', cm_test,'\n')
print('confusion matrix treino\n',cm_train,'\n')
print(classification_report(y_test, pred),'\n')
stop = timeit.default_timer()

print('Programa executado em ',stop - start,'segundos\n')

0.8806646525679759
confusion matrix teste
 [[230   0   0]
 [ 50 160   0]
 [  0  29 193]] 

confusion matrix treino
 [[501   1   0]
 [ 87 435   0]
 [  0  34 485]] 

             precision    recall  f1-score   support

          3       0.82      1.00      0.90       230
         20       0.85      0.76      0.80       210
        100       1.00      0.87      0.93       222

avg / total       0.89      0.88      0.88       662
 

Programa executado em  48.09428869600015 segundos

